# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0003_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_name',
            field=models.CharField(default='string', max_length=255),
            preserve_default=False,
        ),
    ]
