# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='migrationProject.Book'),
        ),
    ]
